<?php

namespace AppBundle\Repository;

/**
 * AgeRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgeRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
