<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Symfony\Component\Form\Form;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFilterRepository($context) {
        if ($context == 'householder') {
            return $this->getEntityManager()
                ->getRepository('AppBundle:Householder');;
        } else {
            return $this->getEntityManager()
                ->getRepository('AppBundle:Housemate');
        }
    }

    public function filterByForm(Form $form)
    {
        $regions = $form->get('regions')->getViewData();
        $minMortgage = $form->get('minMortgage')->getViewData();
        $maxMortgage = $form->get('maxMortgage')->getViewData();
        $minRent = $form->get('minRent')->getViewData();
        $maxRent = $form->get('maxRent')->getViewData();

        $qb = $this->createQueryBuilder('p');

        $qb->where('p.id > 0');

        if (is_array($regions) && count($regions) > 0) {
            $qb->join('p.regions', 'r')
                ->andWhere($qb->expr()->in('r.id',$regions));
        }

        if ($minMortgage) {
            $qb->andWhere('p.minMortgage > :min_mortgage')->setParameter('min_mortgage' , $minMortgage);
        }

        if ($maxMortgage) {
            $qb->andWhere('p.maxMortgage < :max_mortgage')->setParameter('max_mortgage' , $maxMortgage);
        }

        if ($minRent) {
            $qb->andWhere('p.minRent > :min_rent')->setParameter('min_rent' , $minRent);
        }

        if ($maxRent) {
            $qb->andWhere('p.maxRent < :max_rent')->setParameter('max_rent' , $maxRent);
        }

        return $qb;
    }
}
