<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use Symfony\Component\DependencyInjection\Container;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function generateApiKey(User $user, Container $container)
    {
        $apiKey = $container->get('security.encoder_factory')->getEncoder($user)->encodePassword(
            uniqid(), $user->getSalt()
        );
        $user->setApiKey($apiKey);
        $em = $this->getEntityManager();
        $em->persist($user);
        $em->flush();
    }
}
