# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']
    fos_user.doctrine_registry:
        alias: doctrine
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@service_container", "@security.authorization_checker", "@security.token_storage"]
        tags:
            - { name: knp_menu.menu_builder, method: createProfileSidebarMenu, alias: profile_side } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main_menu } # The alias is what is used to retrieve the menu
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: AppBundle\Form\ProfileType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: app_user_profile }
    app.media.factory:
        class: AppBundle\Factory\MediaFactory
    app.form.type.householder:
        class: AppBundle\Form\HouseholderType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: "householder" }
    app.form.type.housemate:
            class: AppBundle\Form\HousemateType
            tags:
                - { name: form.type, alias: "housemate" }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
